name: daily integration test

on:
  pull_request:
  schedule:
  # everyday 11am pacific
    - cron: "0 19 * * *"
  # Have the ability to trigger this job manually
  workflow_dispatch:
  push:
    branches:
      - zpao-integration-test-setup

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash -l -eo pipefail {0}

jobs:
  unit_tests:
    runs-on: 4-core-ubuntu
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: configure aws credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_torchtune_pytorch-multimodal
          aws-region: us-east-1
      - name: Download file froom S3
        run: |
          python3 -m pip install awscli==1.27.69
          mkdir test-artifacts
          aws configure set default.s3.max_concurrent_requests 2500
          aws configure set default.s3.preferred_transfer_client crt
          aws configure set default.s3.target_bandwidth 100Gb/s
          aws s3 cp s3://pytorch-multimodal/llama2-7b/tokenizer.model test-artifacts
          aws s3 cp s3://pytorch-multimodal/llama2-7b/consolidated.00.pth test-artifacts
        timeout-minutes: 30
      - name: Install dependencies
        run: |
          conda install pytorch
          python -m pip install -r requirements.txt
          python -m pip install -r dev-requirements.txt
          python -m pip install -e .
      - name: Run unit tests with coverage
        run: pytest tests --cov=. --cov-report=xml --durations=20 -vv
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
